/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-02-22 22:52:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.visitante.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script type=\"text/javascript\" src=\"resources/visitante/login/sincronizarDados.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"lalala.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper fadeInDown\">\r\n");
      out.write("\t<div id=\"formContent\">\r\n");
      out.write("\t\t<div class=\"fadeIn first\">\r\n");
      out.write("\t\t\t<img src=\"resources/visitante/login/images/download.png\" id=\"icon\" alt=\"User Icon\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fadeIn second\">\r\n");
      out.write("\t\t\t<h6>Tipo de usuário</h6>\r\n");
      out.write("\t\t\t<select id=\"selectBox\" class=\"form-control form-control-sm\">\r\n");
      out.write("\t\t\t\t<option>...</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Cliente</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">ADM</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<input id=\"username\" type=\"text\" class=\"fadeIn second\" name=\"username\" placeholder=\"usuário\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<input id=\"password\" type=\"text\" class=\"fadeIn third\" name=\"password\" autocomplete=\"off\" placeholder=\"senha\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"msg\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"#\" id=\"entrar\" onclick=\"SENAI.biblioteca.changeFunc();\">Entrar</a>\r\n");
      out.write("\t\t<div id=\"EsqueceuAsenha\">\r\n");
      out.write("\t\t\t<a class=\"underlineHover\" onclick = \"SENAI.biblioteca.abrirModal();\" href=\"#\">Esqueceu a senha?</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"msg\"></div>\r\n");
      out.write("<div id=\"exibirModal\" style=\"display: none\">\r\n");
      out.write("\t<label id=\"titulos\">Digite o email cadastrado:</label> \r\n");
      out.write("\t<input class=\"fadeIn third\" id=\"umEmail\" placeholder=\"email\" name=\"email\" type=\"text\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
