/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-02-22 22:54:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.admin.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script type=\"text/javascript\" src=\"main/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"divBuscaMain\">\r\n");
      out.write("\t<input type=\"text\" class=\"form-control\" id=\"searchBar\" placeholder=\"Buscar por título...\" />\r\n");
      out.write("\t<button id=\"searchButton\" OnClick=\"SENAI.biblioteca.buscarLivro()\">Buscar</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"tituloMain\">Biblioteca Arco-Íris</div>\r\n");
      out.write("\t<div id=\"subtituloMain\">Acervo de livros</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"resultadoLivros\" >\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <ul class=\"pagination\">\r\n");
      out.write("    <li class=\"page-item\">\r\n");
      out.write("      <a class=\"first\" href=\"#\"><<</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"page-item\">\r\n");
      out.write("      <a class=\"prev\" href=\"#\"><</a>\r\n");
      out.write("    </li>\r\n");
      out.write("   <li class=\"numbers\">\r\n");
      out.write("   \r\n");
      out.write("   </li>\r\n");
      out.write("    <li class=\"page-item\">\r\n");
      out.write("      <a class=\"next\" href=\"#\">></a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"page-item\">\r\n");
      out.write("      <a class=\"last\" href=\"#\">>></a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<div id=\"exibirLivro\" style=\"display: none\">\r\n");
      out.write("\t<label>Título do livro:</label> \r\n");
      out.write("\t<input readonly class='form-control' id=\"tituloExibir\" name=\"titulo\" type=\"text\">\r\n");
      out.write("\t<label>Descrição:</label> \r\n");
      out.write("\t<input readonly class='form-control' id=\"descExibir\" name=\"descricao\" type=\"text\"> \r\n");
      out.write("\t<label>Quantidade:</label> \r\n");
      out.write("\t<input readonly class='form-control' id=\"qtdadeExibir\" name=\"quantidade\" type=\"text\"> \r\n");
      out.write("\t\r\n");
      out.write("\t<label>Autor:</label> \r\n");
      out.write("\t<input readonly class='form-control' id=\"autorExibir\" name=\"autor\" type=\"text\"> \r\n");
      out.write("\t\r\n");
      out.write("\t<label>Editora:</label> \r\n");
      out.write("\t<input readonly class='form-control' id=\"editoraExibir\" name=\"editora\" type=\"text\"> \r\n");
      out.write("\t<input readonly name=\"idLivro\" id=\"idLivroExibir\" type=\"hidden\">\r\n");
      out.write("</div>\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
